name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Config yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: develop
      - run: yarn install --immutable

      - run: nx workspace-lint
      - run: nx affected --target=lint --parallel=3
      - run: nx affected --target=test --parallel=3 --ci --code-coverage
      - run: nx affected --target=build --parallel=3
